stevens <- read.csv("stevens.csv")
str(stevens)
library(caTools)
set.seed(3000)
split <- sample.split(stevens$Reverse, SplitRatio = 0.7)
Train <- subset(stevens, split ==TRUE)
Test <- subset(stevens, split == FALSE)
install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
library(rpart.plot)
stevenstree <- rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent +
                       LowerCourt + Unconst, data =Train, method = "class", control = rpart.control(minbucket = 25))
prp(stevenstree)
PredictCart <- predict(stevenstree, newdata = Test, type = "class")
table(Test$Reverse, PredictCart)
(41+71)/(41+36+22+71)
library(ROCR)
install.packages("ROCR")
library(ROCR)
PredictROC <- predict(stevenstree, newdata = Test)
PredictROC
pred <- prediction(PredictROC[,2], Test$Reverse)
perf <- performance(pred, "tpr", "fpr")
plot(perf)
install.packages("randomForest")
library(randomForest)

Train$Reverse = as.factor(Train$Reverse)
Test$Reverse = as.factor(Test$Reverse)
StevensForest <- randomForest(Reverse ~ Circuit + Issue + Petitioner + 
                                Respondent + LowerCourt + Unconst, data = Train
                              , nodesize = 25, ntree = 200)
PredictForest <- predict(StevensForest, newdata = Test)
table(Test$Reverse,PredictForest)
(40+75)/(40+37+18+75)
install.packages("caret")
library(caret)
install.packages("e1071")
library(e1071)
fitcontrol <- trainControl(method = "cv", number = 10)
cartGrid <- expand.grid(.cp=(1:50)*0.01)
train(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, method = "rpart", trControl = fitcontrol, tuneGrid = cartGrid)
StevensTreeCV <- rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst,method = "class", data = Train, control = rpart.control(cp = 0.17))
PredictCV <- predict(StevensTreeCV,newdata = Test, type = "class")
table(Test$Reverse, PredictCV)
(59+64)/(59+18+29+64)
